config:
  target: http://10.43.13.23:3000
  phases:
    - duration: 30
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 60
      arrivalRate: 5
      rampTo: 15
      name: Ramp up load
    - duration: 40
      arrivalRate: 15
      rampTo: 40
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
scenarios:
  # This flow simulates fetching the react app times
  - flow:
    - get:
        url: "/"
    - get:
        url: "/favicon.ico"
    - get:
        url: "/manifest.json"
    - get:
        url: "/statictest/test.js"
    - get:
        url: "/statictest/test.css"